#include <stdafx.h>
#include "AudUIPlayer.h"

// Wwise includes
#include <AK/SoundEngine/Common/AkTypes.h>
#include <AK/SoundEngine/Common/AkSoundEngine.h>

#include "AudManager.h"

AudUIPlayer::AudUIPlayer( IRoot* lockobj )
{
	m_ID = UI_GAME_OBJ_ID;
	m_name = "UI";
	CreateWwiseObject();
}

AudUIPlayer::~AudUIPlayer()
{
}

// ---------------------------------------------------------------------------------------
// Description:
//   Sends an event that will trigger the callback defined on m_callback when finished playing.
// Arguments:
//   name - The event to send to the sound engine.
// Return:
//   The playing ID for the event, generated by Wwise. If 0 or below is returned, the event failed to play.
// ----------------------------------------------------------------------------------------
unsigned int AudUIPlayer::SendEventWithCallback( const std::wstring& name )
{
	if( g_audioEnabled )
	{
		m_callbackEventName = PrepareEvent(name, false);
		if(m_callback)
		{
			m_playID = PostEvent( name.c_str(), false, AK_EnableGetSourcePlayPosition );
			g_audioManager->LogPostEvent( m_ID, m_playID, AK_INVALID_UNIQUE_ID, name );
		}
		else 
		{
			CCP_LOGWARN("SendEventWithCallback called without any callback function set");
			return 0;
		}
		return m_playID;
	}
	return 0;
}

// ---------------------------------------------------------------------------------------
// Description:
//   Post an event meant for dialogue. Using this over SendEvent will allow the user to get 
//   the play position of the event using GetEventPlayPosition.
// Arguments:
//   eventName - The event to send to the sound engine.
// Return:
//   The playing ID for the event, generated by Wwise. If 0 or below is returned, the event failed to play.
// ----------------------------------------------------------------------------------------
unsigned int AudUIPlayer::PostDialogueEvent( const std::wstring& eventName )
{
	if( g_audioEnabled )
	{
		return PostEvent( eventName.c_str(), false, AK_EnableGetSourcePlayPosition);
	}
	return 0;
}

//-----------------------------------------------------
// Description:
//   Get the time elapsed in milliseconds of for the given playingID.
// Arguments:
//   playingID - The playing ID of the event to seek. Returned from PostEvent().
// Return Value:
//   The time elapsed in milliseconds. -1 if the playingID is invalid or has finished playing.
//-----------------------------------------------------
int32_t AudUIPlayer::GetEventPlayPosition( const unsigned int playingID )
{
	if ( g_audioInitialized )
	{
		AkTimeMs time = 0;
		AKRESULT result = AK::SoundEngine::GetSourcePlayPosition( playingID, &time ); 
		if ( result != AK_Success )
		{
			time = -1;
		}
		return time;
	}
	return 0;
}

//-----------------------------------------------------
// Description:
//   Call the python callback function defined on this object. Must be called in the 
//   context of the main thread.
// Arguments:
//   pAudUIPlayer - A pointer to the AudUIPlayer object that is calling this function. 
//                  Must be cast to AudUIPlayer* before using it.
//-----------------------------------------------------

void AudUIPlayer::PropagatePythonCallback( void* pAudUIPlayer )
{
	AudUIPlayer* pThis = reinterpret_cast<AudUIPlayer*>( pAudUIPlayer );
	pThis->m_callback.CallVoid( pThis->m_callbackEventName );
}

//-----------------------------------------------------
// Description:
//   An override of the Wwise event callback function. This calls the base class function
//   but also propagates the python callback function defined on this object if there is one.
// Arguments:
//   cbInfo - Callback information from Wwise, see https://www.audiokinetic.com/library/edge/?source=SDK&id=struct_ak_event_callback_info.html 
//-----------------------------------------------------
void AudUIPlayer::EventFinishedCallback( AkEventCallbackInfo* cbInfo )
{
	std::wstring eventName = L"";
	auto found = m_playingEvents.find( cbInfo->playingID );
	if ( found != m_playingEvents.end() )
	{
		eventName = found->second;
	}

	AudGameObjResource::EventFinishedCallback( cbInfo );

	if( m_callback && eventName == m_callbackEventName )
	{
		//This callback comes on the main audiothread which is not the main Python thread.
		//This add will add the callback to the gmainThreadQueue which will be processed on the next tick.
		g_mainThreadQueue->Add( PropagatePythonCallback, this, IBlueCallbackMan::BCBF_NONE, nullptr );	
	}
}